#!/bin/bash

BIN_NAME=${BIN_NAME:-./build/rocm_ernic}
INSTANCES=${INSTANCES:-4}
MANAGER_IP=${MANAGER_IP:-127.0.0.1}
MANAGER_PORT=${MANAGER_PORT:-6320}
KILL_OLD=${KILL_OLD:-false}

  # Function to check if any instances of our process is runing
  # already.

is_process_running() {
    pgrep -f $1 > /dev/null
}

  # A function to generate a random MAC address

gen_mac_address() {
    local mac=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/:$//')
    echo $mac
}

if is_process_running ${BIN_NAME}; then
    if [ $KILL_OLD == "true" ];then
        echo "INFO: Attempting to kill running instance(s)."
        pkill --signal SIGKILL -f ${BIN_NAME}
        sleep 1
        if is_process_running ${BIN_NAME}; then
            echo "ERROR: pkill failed!"
            exit 1
        fi
    else
        echo "ERROR: Instance(s) of ${BIN_NAME} are running."
        pgrep -lf ${BIN_NAME}
        exit 1
    fi
fi

MACS=()
PIDS=()
for (( i=1; i <= ${INSTANCES}; i++ ))
do
    THIS_MAC=$(gen_mac_address)
    if [[ $i -eq 1  ]]; then
        nohup ${BIN_NAME} \
              --socket /tmp/rocm-ernic-${i}.sock \
              --stats-file /tmp/rocm-ernic-${i}.stats \
              --mac ${THIS_MAC} \
              --backend tcp:manager:listen:${MANAGER_PORT} > \
              /tmp/rocm-ernic-${i}.nohup 2>&1 &
    else
        nohup ${BIN_NAME} \
              --socket /tmp/rocm-ernic-${i}.sock \
              --stats-file /tmp/rocm-ernic-${i}.stats \
              --mac ${THIS_MAC} \
              --backend tcp:worker:${MANAGER_IP}:${MANAGER_PORT} > \
              /tmp/rocm-ernic-${i}.nohup 2>&1 &
    fi
    sleep 0.1
    MACS+=(${THIS_MAC})
    PIDS+=($!)
done
echo "INFO: Launched ${INSTANCES} instances of ${BIN_NAME}."
for (( i=0; i < ${INSTANCES}; i++ )); do
    echo "  ${i}:  ${MACS[i]}:  ${PIDS[i]}"
done
