# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_INFINIBAND_AMD_EMRDMA) += amd_emrdma.o

amd_emrdma-y := amd_emrdma_cmd.o amd_emrdma_cq.o amd_emrdma_doorbell.o amd_emrdma_main.o amd_emrdma_misc.o amd_emrdma_mr.o amd_emrdma_qp.o amd_emrdma_srq.o amd_emrdma_verbs.o
